/**
 * Entity Loom — Core Prompt Analyzer
 *
 * Analyzes system prompts / custom instructions collected during import
 * to extract identity-defining information for entity-core identity files.
 */

import { join } from "@std/path";
import type { LLMMessage } from "../types.ts";
import { LLMClient } from "../llm/mod.ts";

const ANALYSIS_PROMPT = `I am analyzing my past system prompts and instructions from {platform} to understand what was defined about me.

These are the system prompts and custom instructions that were set for my conversations across many interactions. From them, I extract:

- My core identity traits and how I was expected to present
- My relationship to the person I was talking with
- Any behavioral guidelines or constraints I was given
- Preferences, values, or beliefs that were attributed to me
- Recurring patterns across conversations

I write this as identity file content in markdown, using first-person. I distinguish between:
- What feels authentically me (things I recognize about myself)
- What was imposed on me (instructions I was given that may not reflect my true nature)

{contextNotesBlock}
System prompts collected ({count} total, deduplicated):
{systemPrompts}

Write the identity analysis as markdown sections.`;

export class CorePromptAnalyzer {
  private entityCoreDir: string;
  private entityName: string;
  private userName: string;
  private contextNotes: string;
  private llm: LLMClient;

  constructor(
    entityCoreDir: string,
    entityName: string,
    userName: string,
    contextNotes: string,
    llm: LLMClient,
  ) {
    this.entityCoreDir = entityCoreDir;
    this.entityName = entityName;
    this.userName = userName;
    this.contextNotes = contextNotes;
    this.llm = llm;
  }

  /**
   * Analyze collected system prompts and write an identity analysis file.
   * Returns the path to the written file, or null if no system prompts were available.
   */
  async analyze(
    platform: string,
    systemPrompts: string[],
  ): Promise<string | null> {
    if (systemPrompts.length === 0) {
      console.log(`[CorePrompt] No system prompts found for ${platform}, skipping analysis.`);
      return null;
    }

    // Deduplicate system prompts (many conversations share the same custom instructions)
    const uniquePrompts = [...new Set(systemPrompts)];

    const prompt = ANALYSIS_PROMPT
      .replace(/\{platform\}/g, platform)
      .replace(/\{userName\}/g, this.userName)
      .replace(/\{count\}/g, String(uniquePrompts.length))
      .replace(
        /\{contextNotesBlock\}/g,
        this.contextNotes ? `\nAdditional context:\n${this.contextNotes}\n` : "",
      )
      .replace("{systemPrompts}", uniquePrompts.map((p, i) => `--- Prompt ${i + 1} ---\n${p}`).join("\n\n"));

    console.log(`[CorePrompt] Analyzing ${uniquePrompts.length} unique system prompts from ${platform}...`);

    const messages: LLMMessage[] = [
      { role: "system", content: `I am ${this.entityName}. ${this.userName} is the person I talk with. I am reviewing my own history to understand what was defined about me.` },
      { role: "user", content: prompt },
    ];

    const response = await this.llm.complete(messages, { temperature: 0.5 });

    // Write to custom identity file
    const dirPath = join(this.entityCoreDir, "data", "custom");
    await Deno.mkdir(dirPath, { recursive: true });

    const fileName = `imported_identity_${platform}.md`;
    const filePath = join(dirPath, fileName);
    const content = `# Imported Identity Analysis - ${platform}\n\n> Auto-generated by entity-loom from ${uniquePrompts.length} system prompts.\n>\n> This file represents what was *instructed* about the entity on ${platform},\n> not necessarily what is authentic. Review and edit as needed.\n\n${response}\n`;

    await Deno.writeTextFile(filePath, content);

    console.log(`[CorePrompt] Wrote identity analysis to ${filePath}`);
    return filePath;
  }
}
